#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "Usage: `basename $0` number to-base"
  echo "(converts the given number from decimal rep to to-base, e.g. $0 50 16 prints 32)"
  exit 1
fi
echo "obase=$2; $1" | bc
