#!/bin/sh
# espeak for the pronunciation audible output and phonetic alphabet string
# dict - the client for the dictionary server
# we prefer "$*" to "$@" here!
dict "$*" | more
#echo "Phoneme mnemonics: $(espeak -ven-us -x "$*" 2> /dev/null)"       
