#!/bin/bash
VER=RubyMine-3.0.1
FILE=$VER.tar.gz
wget http://download-ln.jetbrains.com/ruby/$FILE
tar xvfz $FILE
cd $VER/bin
if [ -f rubymine.sh.bak ]
then
  cp rubymine.sh.bak rubymine.sh
fi
if [ -f rubymine.sh ]
then
  cp rubymine.sh rubymine.sh.bak
  echo "adding JAVA_HOME"
  if [ -z "$JAVA_HOME" ]
  then
    echo "provide JAVA_HOME"
    read JAVA_HOME
  fi
  sed "/JDK 1.6 installation/ a\
    JAVA_HOME=$JAVA_HOME  # added by script" < rubymine.sh  > rubymine.sh.new
  mv rubymine.sh.new rubymine.sh
  chmod +x rubymine.sh
fi
