#!/bin/bash
# See https://askubuntu.com/a/901012/326955
if [ "$#" -ne 1 ]; then
  echo "Usage: $0 some-string-for-the-desktop-program-name-eg-files"
  exit 1
fi
locate -b '.desktop' | xargs grep -ils "^Name.*=$1" | xargs grep '^Exec.*'
