#!/bin/sh
# espeak for the pronunciation audible output and phonetic alphabet string
# only consult the wordnet dictionary with dict
# we prefer "$*" to "$@" here!
dict -d wn "$*" | more
echo "Phoneme mnemonics: $(espeak -ven-us -x "$*" 2> /dev/null)"       
