#!/bin/sh
echo "creates and publishes the tatsu sources cross-referenced"
SRC_DIR=${TATSU}/branch/${CURRENT_BRANCH}
PUB_DIR=${HOME}/tatsuxref
\rm -rf ${PUB_DIR}
mkdir ${PUB_DIR}
MAGIC=${HOME}/Projects/sorcerer/sorcerer-0.7/sorcerer.jar
java -jar ${MAGIC} -d ${PUB_DIR} ${SRC_DIR}/TAS/src
#java -jar ${MAGIC} -d ${PUB_DIR} ${SRC_DIR}/TSS/src
#java -jar ${MAGIC} -d ${PUB_DIR} ${SRC_DIR}/TAS_Receipt_Tool/src
#java -jar ${MAGIC} -d ${PUB_DIR} ${SRC_DIR}/TSS_Receipt_Tool/src
rsync -avz ${PUB_DIR} tatsud@iceman:~/apache-tomcat-5.5.28/webapps/ROOT
