#!/bin/bash

# makes an executable in given name from name.s
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 executable-name"
  exit 1
fi
if [[ $1 =~ ^-.+$ ]]; then
  echo "executable name should not start with a '-'"
  exit 3
fi
if [[ ! -f $1.s ]]; then
  echo "missing $1.s assembly source file"
  exit 2
fi
FILE=$1
as -g -o $FILE.o $FILE.s; ld -o $FILE $FILE.o
